
FROM continuumio/miniconda3 AS build
RUN conda install -c conda-forge conda-pack
COPY test-base-image-environment.yaml .
RUN conda env update -f test-base-image-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY test-base-image.py .

